<a href="https://colab.research.google.com/github/jhonfirefox/Laboratorios_TT/blob/main/Lab7_TT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Parte 1**

El primer ejercicio de práctica deberás realizar el código usando las funciones y bibliotecas Panda en Python, con el respectivo grafico según el caso, escribir el respectivo código y mostrar el resultado, aplicar los temas vistos en clase.

In [1]:
#Crear un DataFrame con los nombres, profesión y países de 8 personas, y luego imprimir el DataFrame.
import pandas as pd

# Crear el diccionario con los datos de las personas
datos = {
    "Nombre": ["Juan Pérez", "Ana López", "Carlos García", "Laura Martínez", "José Rodríguez", "Marta Sánchez", "Pedro Gómez", "Lucía Fernández"],
    "Profesión": ["Ingeniero", "Doctora", "Abogado", "Arquitecta", "Profesor", "Diseñadora", "Músico", "Periodista"],
    "País": ["España", "México", "Argentina", "Colombia", "Chile", "Perú", "Uruguay", "España"]
}

# Crear el DataFrame
df = pd.DataFrame(datos)

# Imprimir el DataFrame
print(df)

            Nombre   Profesión       País
0       Juan Pérez   Ingeniero     España
1        Ana López     Doctora     México
2    Carlos García     Abogado  Argentina
3   Laura Martínez  Arquitecta   Colombia
4   José Rodríguez    Profesor      Chile
5    Marta Sánchez  Diseñadora       Perú
6      Pedro Gómez      Músico    Uruguay
7  Lucía Fernández  Periodista     España


In [2]:
#Cargar un archivo CSV (puedes usar un archivo de ejemplo en tu entorno) y mostrar las primeras 5 filas.
url  = "https://raw.githubusercontent.com/jhonfirefox/Laboratorios_TT/main/Lab1_DA.csv"

Dlist1 = pd.read_csv(url, sep=",", decimal=".", encoding='windows-1252')
Dlist1.head(5)


id     cedula    nombres y apellidos           direccion     celular  \
0  1   45673849           ana gonzalez        cl 2 #123-34  3114562728   
1  2   38755920             berta cruz   carrera 3 # 23-23  3108976542   
2  3  867433939      roberto     rios         cl 32 #45-23  3004567283   
3  4  387575741            mariacastro  carrera 32 # 34-43  3057893245   
4  5   12234421         marrria   rios      cl132 #145-123  3125578930   

      correo electronico        pais valor factura   servicio  \
0           ag@gmail.com    colombia         45000     hogarr   
1      berta@hotmail.com  colombiaaa         34876      rogar   
2                    NaN       chile         23456   comercio   
3      mcastro@yahoo.com      chiles         45000  comerciio   
4  lindatriana@gmail.com      japonn        450000   comercio   

     fecha instalacion comentarios observaciones  
0             5/3/2023           .             .  
1            6/30/2022           *           NaN  
2  8 de junio de 2024.          na           NaN  
3            2021-23-1         NaN           NaN  
4            4/20/2022           .             *

In [3]:
#Generar un DataFrame con 100 filas y 8 columnas de valores aleatorios, y luego mostrar un resumen estadístico de los datos.
import pandas as pd
import numpy as np

# Crear un DataFrame con 100 filas y 8 columnas de valores aleatorios
datos_df = pd.DataFrame(np.random.rand(100, 8))

# Mostrar un resumen estadístico de los datos
print(datos_df.describe())

                0           1           2           3           4           5  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.494496    0.450276    0.492619    0.475300    0.481582    0.476432   
std      0.271308    0.286578    0.287146    0.285319    0.316040    0.296668   
min      0.010975    0.000339    0.007915    0.013349    0.001277    0.012290   
25%      0.268204    0.215530    0.251803    0.260555    0.211150    0.177109   
50%      0.517800    0.452580    0.488000    0.484304    0.451877    0.493655   
75%      0.726061    0.680376    0.743132    0.685847    0.801770    0.741264   
max      0.978686    0.984612    0.991182    0.996519    0.997221    0.986889   

                6           7  
count  100.000000  100.000000  
mean     0.536810    0.487147  
std      0.284189    0.274475  
min      0.008962    0.001728  
25%      0.285078    0.277288  
50%      0.543722    0.482598  
75%      0.771160    0.715776  
max      0.999

# **Parte 2**

El segundo ejercicio de práctica deberás realizar el código usando las funciones y bibliotecas Numpy en Python, con el respectivo grafico según los escenarios, escribir el respectivo código y mostrar el resultado, aplicar los temas vistos en clase.

In [4]:
#Crear un array de números del 1 al 10 y mostrar la suma, la media, y el valor máximo.
numeros = np.arange(1,11)
print("Suma:", np.sum(numeros))
print("Media:", np.mean(numeros))
print("Valor máximo:", np.max(numeros))
#

Suma: 55
Media: 5.5
Valor máximo: 10


In [8]:
#Crear un array de 3x4 lleno de ceros y luego cambiar su forma a 2x6
ceros = np.zeros((3,4))
print("Array original")
print(ceros)

ceros = ceros.reshape(2,6)
print("Array final")
print(ceros)

Array original
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array final
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [9]:
#Generar una matriz aleatoria de 3x3 y calcular su transpuesta.
matriz = np.random.rand(3,3)
print("Matriz original")
print(matriz)

transpuesta = np.transpose(matriz)
print("Matriz transpuesta")
print(transpuesta)

Matriz original
[[0.06167365 0.65528891 0.7761603 ]
 [0.90249589 0.10453889 0.53734132]
 [0.87144397 0.90530169 0.40615249]]
Matriz transpuesta
[[0.06167365 0.90249589 0.87144397]
 [0.65528891 0.10453889 0.90530169]
 [0.7761603  0.53734132 0.40615249]]


In [10]:
#Concatenar dos arrays de NumPy, cada uno con 5 valores, y luego imprimir el array concatenado.
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])

array_concatenado = np.concatenate((array1, array2))
print(array_concatenado)

[ 1  2  3  4  5  6  7  8  9 10]
